# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CoachellaQueen' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoachellaQueen
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Crash'
  pod 'Firebase/Storage'

  target 'CoachellaQueenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
